### ISSUE TITLE
Use of global options

### ISSUE THREAD

**Issue by ZagHe568** [dhcwg/yang#15]
Currently in the server model, options are defined in network-range/pool/host level. However, global options should be used if clients connected to most subnets are expected to get the same values of a given option. Otherwise, it might incur repeated implementations of one option for administrators.

**Comment by bevolz** [comment]
Yes, a global option set should be provided. This can be useful for smaller configurations (i.e., perhaps here is only one set of DNS servers for all clients).


-          Bernie

**Comment by ZagHe568** [comment]
Alright. Now 'dns-server' is under 'network-ranges' and this option is removed from 'option-set'.

**Comment by bevolz** [comment]
I think that’s a bad idea. Why do that?

Network-ranges or pools should be allowed to have an option-set where dns-server can be one of the options, but you should allow dns-server to be in any option-set.

For example, why could I not have one dns-server option for my entire (global) configuration if I have a “smaller” organization that only has a single set of DNS servers.

I can’t see why one would tie dns-servers to only network-ranges.


-          Bernie

**Comment by ZagHe568** [comment]
I see your point here. Maybe it is really a bad idea.
I think we should move 'dns-servers-option' back to 'option-set', and add an 'option-set-id' leaf under 'network-ranges' used as global options.
