### ISSUE TITLE
nis-domain-name/nis-plus-domain-name in odd place?

### ISSUE THREAD

**Issue by bevolz** [dhcwg/yang#16]
For the portion of the server mode:

 |  |   +--rw hosts
 |  |      +--rw host* [cli-id]
 |  |         +--rw cli-id                  uint32
 |  |         +--rw duid
 |  |         |  +--rw type-code?                   uint16
 |  |         |  +--rw (duid-type)?
 |  |         |     +--:(duid-llt)
 |  |         |     |  +--rw duid-llt-hardware-type?      uint16
 |  |         |     |  +--rw duid-llt-time?        yang:timeticks
 |  |         |     |  +--rw duid-llt-link-layer-addr?  yang:mac-address
 |  |         |     +--:(duid-en)
 |  |         |     |  +--rw duid-en-enterprise-number?  uint32
 |  |         |     |  +--rw duid-en-identifier?         string
 |  |         |     +--:(duid-ll)
 |  |         |     |  +--rw duid-ll-hardware-type?     uint16
 |  |         |     |  +--rw duid-ll-link-layer-addr?  yang:mac-address
 |  |         |     +--:(duid-uuid)
 |  |         |     |  +--rw uuid?                        yang:uuid
 |  |         |     +--:(duid-invalid)
 |  |         |        +--rw data?                        binary
 |  |         +--rw inherit-option-set      boolean
 |  |         +--rw option-set-id?
                  -> /server/server-config/option-sets/option-set/id
 |  |         +--rw nis-domain-name?        string
 |  |         +--rw nis-plus-domain-name?   string

Why these last 2 (nis-domain-name, nis-llus-domain-name)? Wouldn't this be covered by the option-set?

**Comment by ZagHe568** [comment]
Oh, these 2 were intended to be only configured at host level. In version 05, to keep the model more uniform, we added them to the option-set but forgot to deleted them from here. :-)
I'll delete them in next version.
