### ISSUE TITLE
hackathon101: s46-v4-v6-binding-option has incorrect field types

### ISSUE THREAD

**Issue by tomaszmrugalski** [dhcwg/yang#24]
Ok, this one a bit tricky. The RFC7598 defines v4-v6 binding option (code 92) it defines 3 fields: ipv-4addres (defined correctly),  bindprefix6-len (defined correctly) and bind-ipv6-prefix (which is defined incorrectly in the model). Despite its name, it contains a variable amount of leading bits (up to 128), but it does not contain a prefix length. That's what bindprefix6-len is for.

You can either turn the bind-ipv6-prefix type to ipv6-address or remove bindprefix6-len as separate field. I think the former is cleaner, but I would be ok with going with the latter.

**Comment by ZagHe568** [comment]
OK. Thanks for your reminding.

**Comment by iffy50** [comment]
This has been changed to ipv6-address in -07. Not sure who did it, but thanks!
