### ISSUE TITLE
option-set-id inconsistency

### ISSUE THREAD

**Issue by fxdupont** [dhcwg/yang#30]
Uses of option-set-id are inconsistent:
 - optional in network ranges (container), network range (list element) and host reservation
 - mandatory in address and pd pools
In fact you have two choices:
 - make it mandatory everywhere and suggest to define an empty option-set with for instance id 0
 - make it optional everywhere
Of course I am in favor of the second solution I'll implement in a PR.

**Comment by tomaszmrugalski** [comment]
The second proposal is obviously the way to go. This is how every DHCP server I'm familiar with operates. While options are almost always used, they are not necessary from the protocol or implementation perspective.

Also, making them optional was what we did during a hackathon.

So +1 for making it optional everywhere.
