### ISSUE TITLE
Address/Prefix Pool Utilization 

### ISSUE THREAD

**Issue by dhcwg** [dhcwg/yang#5]
The intended function of the address/prefix pool utilization is to have a configurable threshold value which can be compared to the current pool utilization threshold (under the state tree). These are then used by the notifications section.

In the current model, the nodes around threshold are not defined this way and the logic for the notification needs to be added.

**Comment by ZagHe568** [comment]
Now ‘max-address/prefix-utilization-ratio’ is a configurable threshold value under 'server-config', and ‘address/prefix-utilization-ratio’ is under 'server-state' indicating current utilization ratio which is not configurable. These are used by notifications. I think this is a possible logic.

By the way, since 'address-pool' and 'prefix-pool' are independent for , should we split the notification 'pool-running-out' into 'address-pool-running-out' and 'prefix-pool-running-out'?

**Comment by bevolz** [comment]
Either have the two different notifications or provide an indication in the notification of the type?

BTW: I have to study these notifications a bit more. For addresses, using lease counts against the maximum seems sufficient. For prefix delegation, especially if variable length prefixes are allowed (i.e., a pool is not all of one prefix length), a count may not be that useful – instead, you’d like to use the percentage of the PD space used. Perhaps having both types (a count of “leases” and a usage) would be best for PD pools?


-          Bernie

**Comment by ZagHe568** [comment]
Well, I mean we have two different notifications. Currently the container is 'pool-running-out', I'd like to split it into two containers 'address-pool-running-out' and 'pd-pool-running-out'.
Yes, maybe for addresses count alone is enough. But I don't understand why count is not useful for prefix delegation. Wouldn't the percentage of the PD space used actually be calculated from the counts of total prefixes and allocated prefixes, even though there are variable-length prefixes in a pd-pool?

**Comment by bevolz** [comment]
OK on splitting the notifications, though a more generalized approach would be to say “pool-low-threshold-reached” and specify details about the pool. If we have yet another type of resource, specifying something about the pool (name and IA_* type) might be more generic though? But I don’t think it is a big deal either way.

Counts are OK as one of the triggers for PD, but if variable prefix lengths are allowed, a count may not represent the “percentage” of space actually used. A count works best to fixed prefix lengths (or addresses).


-          Bernie
