### ISSUE TITLE
Interactions with ietf-interfaces

### ISSUE THREAD

**Issue by dhcwg** [dhcwg/yang#7]
All of the models should have some interaction with ietf-interfaces, either for which interface configuration is being requested for (client), or where the function is listening (relay/server). References to /if:interfaces/if:interface: needs to be added for this.

**Comment by ZagHe568** [comment]
Now interfaces in this model looks like this (some nodes are not listed here.) 'if:interface-ref' indicates the references to ietf-interfaces.

server
       |  +--rw serv-attributes
       |  |  +--rw interfaces-config*   if:interface-ref

client
       |  +--rw client-if* [if-name]
       |     +--rw if-name                      if:interface-ref
       |     +--rw cli-id                       uint32
       |     +--rw pd-function                  boolean
       |     +--rw rapid-commit                 boolean

relay
       |  +--rw relay-if* [if-name]
       |     +--rw if-name               if:interface-ref
       |     +--rw interface-id?         string
       |     +--rw ipv6-address?         inet:ipv6-address
       |     +--rw rsoo-option-set-id?   -> /relay/relay-config/rsoo-option-sets/option-set/id
       |     +--rw next-entity* [dest-addr]
       |        +--rw dest-addr    inet:ipv6-address
       |        +--rw available    boolean
       |        +--rw multicast    boolean
       |        +--rw server       boolean
